# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Ian Quain
first_name: Ian
last_name: Quain
description: >- # ignore newlines
  Ian Quain's personal archive. Built to serve as a developer portfolio and blog.
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

email: you@example.com
github: https://github.com/quaini
linkedin: https://www.linkedin.com/in/ianquain/
stackoverflow: https://stackoverflow.com/users/
youtube: https://www.youtube.com/channel/

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  posts:
    defaults:
      layout: blog
    output: true
    permalink: /blog/:path/
  projects:
    defaults:
      layout: projects
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Plug-ins
plugins:
  - jekyll-feed
